/**
 * サンプルデータ（参考用）
 * level: national | prefecture | municipality
 * prefectureCode: JIS都道府県コード（全国対象は null）
 * cityCodes: 対象の全国地方公共団体コード（6桁）の配列。null は「県全体または未細分化」
 * sourceUrls: 任意。公式以外の省庁・公社・他サイトなど、横断的に探すための参考URL（officialUrl に加えて取得・表示）
 */
window.SUBSIDY_REFERENCE_DATA = {
  /** JIS X 0401 都道府県コード（1〜47、表示は2桁ゼロ埋め） */
  prefectures: [
    { code: "01", name: "北海道" },
    { code: "02", name: "青森県" },
    { code: "03", name: "岩手県" },
    { code: "04", name: "宮城県" },
    { code: "05", name: "秋田県" },
    { code: "06", name: "山形県" },
    { code: "07", name: "福島県" },
    { code: "08", name: "茨城県" },
    { code: "09", name: "栃木県" },
    { code: "10", name: "群馬県" },
    { code: "11", name: "埼玉県" },
    { code: "12", name: "千葉県" },
    { code: "13", name: "東京都" },
    { code: "14", name: "神奈川県" },
    { code: "15", name: "新潟県" },
    { code: "16", name: "富山県" },
    { code: "17", name: "石川県" },
    { code: "18", name: "福井県" },
    { code: "19", name: "山梨県" },
    { code: "20", name: "長野県" },
    { code: "21", name: "岐阜県" },
    { code: "22", name: "静岡県" },
    { code: "23", name: "愛知県" },
    { code: "24", name: "三重県" },
    { code: "25", name: "滋賀県" },
    { code: "26", name: "京都府" },
    { code: "27", name: "大阪府" },
    { code: "28", name: "兵庫県" },
    { code: "29", name: "奈良県" },
    { code: "30", name: "和歌山県" },
    { code: "31", name: "鳥取県" },
    { code: "32", name: "島根県" },
    { code: "33", name: "岡山県" },
    { code: "34", name: "広島県" },
    { code: "35", name: "山口県" },
    { code: "36", name: "徳島県" },
    { code: "37", name: "香川県" },
    { code: "38", name: "愛媛県" },
    { code: "39", name: "高知県" },
    { code: "40", name: "福岡県" },
    { code: "41", name: "佐賀県" },
    { code: "42", name: "長崎県" },
    { code: "43", name: "熊本県" },
    { code: "44", name: "大分県" },
    { code: "45", name: "宮崎県" },
    { code: "46", name: "鹿児島県" },
    { code: "47", name: "沖縄県" },
  ],
  programs: [
    {
      id: "nat-it",
      title: "IT導入補助金（デジタル化・業務効率化の枠組みの一例）",
      level: "national",
      prefectureCode: null,
      cityCodes: null,
      tags: ["IT", "業務効率"],
      summary:
        "診療・介護記録、請求、シフト管理等のシステム導入を検討する事業者向けの公的支援の一例。業種・規模・採択要件は公募ごとに異なります。",
      note: "訪問看護ステーションが要件を満たす場合に検討余地あり。最新の公募要領で要確認。",
      officialUrl: "https://www.it-hojo.jp/",
      sourceUrls: [
        "https://www.meti.go.jp/policy/sme_chi/sme/index.html",
        "https://portal.jizokuka-portal.go.jp/",
      ],
      lastVerified: "2026-04-01",
    },
    {
      id: "nat-chusho",
      title: "中小企業庁の支援制度ポータル（設備・人材・資金など横断検索）",
      level: "national",
      prefectureCode: null,
      cityCodes: null,
      tags: ["中小企業", "横断検索"],
      summary:
        "設備投資、人材育成、経営改善など、中小企業向けの制度を横断的に探すための入口。法人形態・従業員数等で対象が変わります。",
      note: "医療法人・社会福祉法人等は対象外の制度も多い。法人種別ごとに要確認。",
      officialUrl: "https://www.chusho.meti.go.jp/",
      sourceUrls: [
        "https://www.meti.go.jp/policy/sme_chi/sme/index.html",
        "https://www.jfc.go.jp/n/finance/index.html",
      ],
      lastVerified: "2026-04-01",
    },
    {
      id: "nat-mhlw",
      title: "厚生労働省（医療・介護・福祉関連の政策・公募情報）",
      level: "national",
      prefectureCode: null,
      cityCodes: null,
      tags: ["医療・介護", "政策", "福祉"],
      summary:
        "介護保険・高齢者福祉など国の福祉・介護政策、医療政策の入口。訪問看護に関する制度変更や関連公募は、福祉・介護の分野ページから辿ることが多いです。",
      note: "都道府県・市区町村の福祉局・保健福祉部独自の助成・公募は各自治体サイトでも確認してください（本ページの地域別候補と併用）。",
      officialUrl: "https://www.mhlw.go.jp/",
      sourceUrls: [
        "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryou/index.html",
        "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/index.html",
        "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/kaigo_koureisha/index.html",
      ],
      lastVerified: "2026-04-04",
    },
    {
      id: "tokyo-fukushi",
      title: "東京都福祉局（高齢・障害福祉・介護に関する行政情報）",
      level: "prefecture",
      prefectureCode: "13",
      cityCodes: null,
      tags: ["東京都", "福祉局", "介護"],
      summary:
        "東京都の福祉行政の公式サイト。高齢者福祉・障害福祉・介護保険・事業者向け周知などは分野別ページに整理されています。訪問看護に関する都の独自制度や公募は、サイト内検索や「介護」「事業者」等のキーワードで探す必要があることがあります。",
      note: "補助金・助成の名称は年度で変わることがあります。必ず最新の公募要領を公式で確認してください。",
      officialUrl: "https://www.fukushi.metro.tokyo.lg.jp/",
      sourceUrls: [
        "https://www.fukushi.metro.tokyo.lg.jp/kourei/index.html",
        "https://www.fukushi.metro.tokyo.lg.jp/shougai/index.html",
      ],
      lastVerified: "2026-04-04",
    },
    {
      id: "tokyo-sme",
      title: "東京都 中小企業向け支援（例：都独自の制度・相談窓口）",
      level: "prefecture",
      prefectureCode: "13",
      cityCodes: null,
      tags: ["東京都", "中小企業"],
      summary:
        "都内事業者向けの融資・補助・相談窓口の案内。区市町村の制度と併せて確認が必要です。",
      note: "サンプルとしてのリンク先。実運用では都の最新の事業者向け一覧URLに差し替え。",
      officialUrl: "https://www.metro.tokyo.lg.jp/",
      sourceUrls: [
        "https://www.smrj.go.jp/",
        "https://www.tokyo-kosha.or.jp/",
      ],
      lastVerified: "2026-04-01",
    },
    {
      id: "tokyo-shibuya",
      title: "渋谷区 事業者向け支援（サンプル：区独自制度のイメージ）",
      level: "municipality",
      prefectureCode: "13",
      cityCodes: ["131130"],
      tags: ["区市町村", "創業・設備", "福祉"],
      summary:
        "区の公式サイト。産業・創業支援のほか、福祉・介護・子育て等の助成は別の分野ページに掲載されることがあります。",
      note: "区の福祉担当（福祉保健・高齢・介護など）の案内から、訪問看護・介護事業者向けの独自枠を探すとよいです。",
      officialUrl: "https://www.city.shibuya.tokyo.jp/",
      sourceUrls: ["https://www.city.shibuya.tokyo.jp/genre/business/index.html"],
      lastVerified: "2026-04-01",
    },
    {
      id: "kanagawa-pref",
      title: "神奈川県 事業者向け支援・融資情報（サンプル）",
      level: "prefecture",
      prefectureCode: "14",
      cityCodes: null,
      tags: ["神奈川県", "福祉・保健"],
      summary:
        "県の総合ポータル。中小企業向け支援に加え、福祉局・保健福祉系の助成・公募はメニューやサイト内検索（「介護」「福祉」「助成」等）から辿ることが多いです。",
      note: "訪問看護に特化した一覧ページが無い場合があります。福祉・介護担当部局の案内を起点にしてください。",
      officialUrl: "https://www.pref.kanagawa.jp/",
      sourceUrls: ["https://www.kanagawa-seisha.or.jp/top/"],
      lastVerified: "2026-04-01",
    },
    {
      id: "osaka-pref",
      title: "大阪府 中小企業・創業支援（サンプル）",
      level: "prefecture",
      prefectureCode: "27",
      cityCodes: null,
      tags: ["大阪府", "福祉・保健"],
      summary:
        "府の公式ポータル。中小企業支援のほか、介護・障害福祉など福祉保健系の制度・助成は府サイト内の該当部局ページから確認する形が一般的です。",
      note: "訪問看護ステーション向けの枠は、福祉・医療のどちらの助成かで窓口が分かれることがあります。",
      officialUrl: "https://www.pref.osaka.lg.jp/",
      sourceUrls: ["https://www.osaka-sed-bank.jp/"],
      lastVerified: "2026-04-01",
    },
    {
      id: "fukuoka-city",
      title: "福岡市 中小企業等向け支援（サンプル）",
      level: "municipality",
      prefectureCode: "40",
      cityCodes: ["401307"],
      tags: ["福岡市", "福祉・保健"],
      summary:
        "市の公式サイト。産業振興・中小企業向けのほか、保健所・福祉分野の助成・公募は別セクションに掲載されることが多いです。",
      note: "福祉局（または担当部局）・保健所の案内から、介護・訪問看護関連の制度をあわせて確認してください。",
      officialUrl: "https://www.city.fukuoka.lg.jp/",
      sourceUrls: ["https://www.city.fukuoka.lg.jp/soumu/jigyoushien/"],
      lastVerified: "2026-04-01",
    },
  ],
};

window.SUBSIDY_REFERENCE_DATA.municipalities =
  typeof window.MUNICIPALITY_BY_PREF !== "undefined" ? window.MUNICIPALITY_BY_PREF : {};
