/**
 * サンプルデータ（参考用）
 * level: national | prefecture | municipality
 * prefectureCode: JIS都道府県コード（全国対象は null）
 * cityCodes: 対象の全国地方公共団体コード（6桁）の配列。null は「県全体または未細分化」
 * sourceUrls: 任意。公式以外の省庁・公社・他サイトなど、横断的に探すための参考URL（officialUrl に加えて取得・表示）
 */
window.SUBSIDY_REFERENCE_DATA = {
  /** JIS X 0401 都道府県コード（1〜47、表示は2桁ゼロ埋め） */
  prefectures: [
    { code: "01", name: "北海道" },
    { code: "02", name: "青森県" },
    { code: "03", name: "岩手県" },
    { code: "04", name: "宮城県" },
    { code: "05", name: "秋田県" },
    { code: "06", name: "山形県" },
    { code: "07", name: "福島県" },
    { code: "08", name: "茨城県" },
    { code: "09", name: "栃木県" },
    { code: "10", name: "群馬県" },
    { code: "11", name: "埼玉県" },
    { code: "12", name: "千葉県" },
    { code: "13", name: "東京都" },
    { code: "14", name: "神奈川県" },
    { code: "15", name: "新潟県" },
    { code: "16", name: "富山県" },
    { code: "17", name: "石川県" },
    { code: "18", name: "福井県" },
    { code: "19", name: "山梨県" },
    { code: "20", name: "長野県" },
    { code: "21", name: "岐阜県" },
    { code: "22", name: "静岡県" },
    { code: "23", name: "愛知県" },
    { code: "24", name: "三重県" },
    { code: "25", name: "滋賀県" },
    { code: "26", name: "京都府" },
    { code: "27", name: "大阪府" },
    { code: "28", name: "兵庫県" },
    { code: "29", name: "奈良県" },
    { code: "30", name: "和歌山県" },
    { code: "31", name: "鳥取県" },
    { code: "32", name: "島根県" },
    { code: "33", name: "岡山県" },
    { code: "34", name: "広島県" },
    { code: "35", name: "山口県" },
    { code: "36", name: "徳島県" },
    { code: "37", name: "香川県" },
    { code: "38", name: "愛媛県" },
    { code: "39", name: "高知県" },
    { code: "40", name: "福岡県" },
    { code: "41", name: "佐賀県" },
    { code: "42", name: "長崎県" },
    { code: "43", name: "熊本県" },
    { code: "44", name: "大分県" },
    { code: "45", name: "宮崎県" },
    { code: "46", name: "鹿児島県" },
    { code: "47", name: "沖縄県" },
  ],
  programs: [
    {
      id: "nat-it",
      title: "IT導入補助金（デジタル化・業務効率化の枠組みの一例）",
      level: "national",
      prefectureCode: null,
      cityCodes: null,
      tags: ["IT", "業務効率"],
      summary:
        "診療・介護記録、請求、シフト管理等のシステム導入を検討する事業者向けの公的支援の一例。業種・規模・採択要件は公募ごとに異なります。",
      note: "訪問看護ステーションが要件を満たす場合に検討余地あり。最新の公募要領で要確認。",
      officialUrl: "https://www.it-hojo.jp/",
      sourceUrls: [
        "https://www.meti.go.jp/policy/sme_chi/sme/index.html",
        "https://portal.jizokuka-portal.go.jp/",
      ],
      lastVerified: "2026-04-01",
    },
    {
      id: "nat-chusho",
      title: "中小企業庁の支援制度ポータル（設備・人材・資金など横断検索）",
      level: "national",
      prefectureCode: null,
      cityCodes: null,
      tags: ["中小企業", "横断検索"],
      summary:
        "設備投資、人材育成、経営改善など、中小企業向けの制度を横断的に探すための入口。法人形態・従業員数等で対象が変わります。",
      note: "医療法人・社会福祉法人等は対象外の制度も多い。法人種別ごとに要確認。",
      officialUrl: "https://www.chusho.meti.go.jp/",
      sourceUrls: [
        "https://www.meti.go.jp/policy/sme_chi/sme/index.html",
        "https://www.jfc.go.jp/n/finance/index.html",
      ],
      lastVerified: "2026-04-01",
    },
    {
      id: "nat-mhlw",
      title: "厚生労働省（医療・介護・福祉関連の政策・公募情報）",
      level: "national",
      prefectureCode: null,
      cityCodes: null,
      tags: ["医療・介護", "政策", "福祉"],
      summary:
        "介護保険・高齢者福祉など国の福祉・介護政策、医療政策の入口。訪問看護に関する制度変更や関連公募は、福祉・介護の分野ページから辿ることが多いです。",
      note: "都道府県・市区町村の福祉局・保健福祉部独自の助成・公募は各自治体サイトでも確認してください（本ページの地域別候補と併用）。",
      officialUrl: "https://www.mhlw.go.jp/",
      sourceUrls: [
        "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryou/index.html",
        "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/index.html",
        "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/kaigo_koureisha/index.html",
      ],
      lastVerified: "2026-04-04",
    },
    {
      id: "nat-jititai-hp",
      title: "都道府県・市区町村の公式ホームページ一覧（厚生労働省）",
      level: "national",
      prefectureCode: null,
      cityCodes: null,
      tags: ["全地域", "公式リンク集", "調査の起点"],
      summary:
        "都道府県・指定都市・中核市等の公式サイトへのリンク集です。各サイトで「保健福祉部」「福祉局」「介護保険課」「事業者の方へ」「助成・補助」などから、訪問看護・介護事業者向けの独自制度を追うための出発点になります。",
      note: "都道府県庁の入口カードは全都道府県分あります（東京都は data.js 側の詳細カードと併用）。市区町村単位の独自制度は各市の公式サイトでも要確認です。",
      officialUrl: "https://www.mhlw.go.jp/topics/syokuchu/kanren/hp/jititai.html",
      sourceUrls: [
        "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/iryouhoken/jimusyo_itiran.html",
      ],
      lastVerified: "2026-04-03",
    },
    {
      id: "tokyo-fukushi",
      title: "東京都福祉局（高齢・障害福祉・介護に関する行政情報）",
      level: "prefecture",
      prefectureCode: "13",
      cityCodes: null,
      tags: ["東京都", "福祉局", "介護"],
      summary:
        "東京都の福祉行政の公式サイト。訪問看護ステーション向けの手厚い支援として、高齢者福祉分野に「訪問看護推進総合事業」（補助金・研修の総合案内）が掲載されています。その他、障害福祉・介護保険・事業者向け周知は分野別ページに整理されています。",
      note: "補助金・助成の名称は年度で変わります。必ず最新の公募要領を公式で確認してください。口頭・業界用語の俗称と公式事業名が一致しない場合があります。",
      officialUrl: "https://www.fukushi.metro.tokyo.lg.jp/",
      sourceUrls: [
        "https://www.fukushi.metro.tokyo.lg.jp/kourei/hoken/houkan",
        "https://www.fukushi.metro.tokyo.lg.jp/kourei/index.html",
        "https://www.fukushi.metro.tokyo.lg.jp/shougai/index.html",
      ],
      lastVerified: "2026-04-03",
    },
    {
      id: "tokyo-houkan-r7",
      title: "令和7年度 訪問看護推進総合事業（東京都福祉局・補助金・研修の全体案内）",
      level: "prefecture",
      prefectureCode: "13",
      cityCodes: null,
      tags: ["東京都", "福祉局", "訪問看護", "補助金"],
      summary:
        "東京都福祉局がまとめる、訪問看護ステーション向けの総合支援パッケージの案内ページです。令和7年度は、代替職員（産休等）確保、事務職員雇用支援、新任訪問看護師育成支援、認定訪問看護師資格取得支援などの補助事業に加え、人材確保・教育関連の研修事業へのリンクがあります。電子申請は jGrants を案内している事業があります。",
      note: "「サプライト」等の名称は特定の民間事業所名や俗称である場合があり、都の公式制度名（本ページおよび各 PDF 要領）と一致しません。適用可否は各要綱で確認してください。",
      officialUrl: "https://www.fukushi.metro.tokyo.lg.jp/kourei/hoken/houkan/7sougoujigyougaiyou",
      sourceUrls: [
        "https://www.fukushi.metro.tokyo.lg.jp/kourei/hoken/houkan/7daitai",
        "https://www.fukushi.metro.tokyo.lg.jp/kourei/hoken/houkan/7jimu",
        "https://www.fukushi.metro.tokyo.lg.jp/kourei/hoken/houkan/7ikusei",
        "https://www.fukushi.metro.tokyo.lg.jp/kourei/hoken/houkan/7nintei",
        "https://www.jgrants-portal.go.jp/",
      ],
      lastVerified: "2026-04-03",
    },
    {
      id: "tokyo-houmon-kaigo-taisei",
      title: "訪問介護等サービス提供体制確保支援事業（東京都福祉局・介護保険分野）",
      level: "prefecture",
      prefectureCode: "13",
      cityCodes: null,
      tags: ["東京都", "福祉局", "訪問介護", "体制確保"],
      summary:
        "東京都福祉局の介護保険制度関連ページです。訪問「看護」とは別に、訪問介護等のサービス提供体制確保に関する都の支援・周知がまとまっている場合があります（年度により名称・内容が変わります）。",
      note: "訪問看護ステーションと訪問介護事業ではサービス種別・窓口が異なります。自事業の指定区分に合うか、担当課で確認してください。",
      officialUrl: "https://www.fukushi.metro.tokyo.lg.jp/kourei/hoken/houmonkaigoservice",
      sourceUrls: ["https://www.fukushi.metro.tokyo.lg.jp/kourei/hoken/houkan"],
      lastVerified: "2026-04-03",
    },
    {
      id: "tokyo-hoken-zaitaku",
      title: "在宅療養（東京都保健医療局）",
      level: "prefecture",
      prefectureCode: "13",
      cityCodes: null,
      tags: ["東京都", "保健医療局", "在宅"],
      summary:
        "東京都保健医療局の在宅療養・退院支援等の案内です。訪問看護と連動した医療側の施策やマニュアルへのリンクがあり、福祉局の訪問看護推進事業とあわせて参照する用途があります。",
      note: "補助・助成の窓口は施策ごとに福祉局・保健医療局などに分かれることがあります。",
      officialUrl: "https://www.hokeniryo.metro.tokyo.lg.jp/iryo/iryo_hoken/zaitakuryouyou/index.html",
      sourceUrls: [
        "https://www.hokeniryo.metro.tokyo.lg.jp/iryo/iryo_hoken/zaitakuryouyou/taiinnshienn.html",
      ],
      lastVerified: "2026-04-03",
    },
    {
      id: "tokyo-kaigo-bukkakoutou-r7",
      title: "介護サービス事業所向け 物価高騰緊急対策等（東京都福祉局・年度により更新）",
      level: "prefecture",
      prefectureCode: "13",
      cityCodes: null,
      tags: ["東京都", "福祉局", "介護事業所", "物価高騰"],
      summary:
        "東京都が介護サービス事業所向けに周知する物価高騰対策等の案内（掲載 URL・事業名は年度で更新されることがあります）。区市町村の給付金・補助と併給可否が異なる場合があるため、都と市の双方で要確認です。",
      note: "町田市の事業者向けページから、都の同系施策へのリンクが示されていました。受付終了後も、次年度以降の類似枠を探す手がかりにできます。",
      officialUrl: "https://www.fukushi.metro.tokyo.lg.jp/kourei/kaigo_r7bukkakoutou",
      sourceUrls: [
        "https://www.fukushi.metro.tokyo.lg.jp/kourei/shisetu/bukkakoutou7",
      ],
      lastVerified: "2026-04-03",
    },
    {
      id: "tokyo-sme",
      title: "東京都 中小企業向け支援（例：都独自の制度・相談窓口）",
      level: "prefecture",
      prefectureCode: "13",
      cityCodes: null,
      tags: ["東京都", "中小企業"],
      summary:
        "都内事業者向けの融資・補助・相談窓口の案内。区市町村の制度と併せて確認が必要です。",
      note: "サンプルとしてのリンク先。実運用では都の最新の事業者向け一覧URLに差し替え。",
      officialUrl: "https://www.metro.tokyo.lg.jp/",
      sourceUrls: [
        "https://www.smrj.go.jp/",
        "https://www.tokyo-kosha.or.jp/",
      ],
      lastVerified: "2026-04-01",
    },
    {
      id: "tokyo-shibuya",
      title: "渋谷区 事業者向け支援（サンプル：区独自制度のイメージ）",
      level: "municipality",
      prefectureCode: "13",
      cityCodes: ["131130"],
      tags: ["区市町村", "創業・設備", "福祉"],
      summary:
        "区の公式サイト。産業・創業支援のほか、福祉・介護・子育て等の助成は別の分野ページに掲載されることがあります。",
      note: "区の福祉担当（福祉保健・高齢・介護など）の案内から、訪問看護・介護事業者向けの独自枠を探すとよいです。",
      officialUrl: "https://www.city.shibuya.tokyo.jp/",
      sourceUrls: ["https://www.city.shibuya.tokyo.jp/genre/business/index.html"],
      lastVerified: "2026-04-01",
    },
    {
      id: "machida-kaigo-jigyosha",
      title: "町田市 介護保険に関する事業者の方向け（指定・助成・周知の入口）",
      level: "municipality",
      prefectureCode: "13",
      cityCodes: ["132098"],
      tags: ["町田市", "介護事業者", "保健所・介護"],
      summary:
        "町田市公式サイトの介護事業者向けセクションです。物価高騰対策の給付・申請（年度・受付期間付き）、指定・届出、研修、加算様式など、市指定の介護・地域密着型等の事業者向け情報の入口になります。訪問看護ステーションは、都の「訪問看護推進総合事業」との併用可否を各要領で確認してください。",
      note: "例として掲載した物価高騰対策支援給付金は、掲載時点では申請受付終了後のページでした。最新の助成は本一覧から辿れる各お知らせを確認してください。",
      officialUrl: "https://www.city.machida.tokyo.jp/iryo/kaigo/business/index.html",
      sourceUrls: [
        "https://www.city.machida.tokyo.jp/iryo/kaigo/business/bukkakofusinsei.html",
        "https://www.city.machida.tokyo.jp/iryo/syougai_hukushi/nitijoseikatsushien/homon/hokan.html",
      ],
      lastVerified: "2026-04-03",
    },
    {
      id: "fukuoka-city",
      title: "福岡市 中小企業等向け支援（サンプル）",
      level: "municipality",
      prefectureCode: "40",
      cityCodes: ["401307"],
      tags: ["福岡市", "福祉・保健"],
      summary:
        "市の公式サイト。産業振興・中小企業向けのほか、保健所・福祉分野の助成・公募は別セクションに掲載されることが多いです。",
      note: "福祉局（または担当部局）・保健所の案内から、介護・訪問看護関連の制度をあわせて確認してください。",
      officialUrl: "https://www.city.fukuoka.lg.jp/",
      sourceUrls: ["https://www.city.fukuoka.lg.jp/soumu/jigyoushien/"],
      lastVerified: "2026-04-01",
    },
  ],
};

window.SUBSIDY_REFERENCE_DATA.municipalities =
  typeof window.MUNICIPALITY_BY_PREF !== "undefined" ? window.MUNICIPALITY_BY_PREF : {};
